const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log('languages array', languages);
const firstElement = languages[0];
console.log('the first element of the array is html', firstElement);
const thirdElement = languages[2];
console.log('the 3rd element of the array is javascript', thirdElement);
const length = 6;
console.log('The length of the array is', length);
const lastElement = languages[languages.length - 1];
console.log('The last element of the array is', lastElement);
